[package]
name = "manta"
version = "0.1.0"
edition = "2024"

[dependencies]

clap = { version = "4.4", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
